### PR TITLE
Modifications to get compiled in msys2 on arm64

### PR DESCRIPTION
**Pull request by superxkooda**
These modifications make it possible to compile within a msys2 clangarm64 environment.

Command used to build:
```
    scons use_mingw=True use_llvm=True arch=arm64
```

The patch file prevents this error from occurring:
```
    gcc -o godot-mesa/src/microsoft/compiler/nir_to_dxil.windows.arm64.o -c -std=c11 -O3 -DMINGW_ENABLED -DWINVER=0x0603 -D_WIN32_WINNT=0x0603 -D__MSVCRT_VERSION__=1792 -DHAVE_STRUCT_TIMESPEC -DWINDOWS_NO_FUTEX -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DPACKAGE_VERSION=\"23.1.0-devel\" -DPACKAGE_BUGREPORT=\"https://gitlab.freedesktop.org/mesa/mesa/-/issues\" -DPIPE_SUBSYSTEM_WINDOWS_USER -D_USE_MATH_DEFINES -DHAVE_TIMESPEC_GET -DHAVE_STRUCT_TIMESPEC -D_UCRT -Igodot-mesa -Igodot-mesa/bin -Igodot-mesa/include -Igodot-mesa/include/GL -Igodot-mesa/include/GLES -Igodot-mesa/include/GLES2 -Igodot-mesa/include/GLES3 -Igodot-mesa/include/KHR -Igodot-mesa/src -Igodot-mesa/src/c11/impl -Igodot-mesa/src/compiler -Igodot-mesa/src/compiler/glsl -Igodot-mesa/src/compiler/nir -Igodot-mesa/src/compiler/nir/__pycache__ -Igodot-mesa/src/compiler/spirv -Igodot-mesa/src/gallium -Igodot-mesa/src/gallium/include -Igodot-mesa/src/gallium/include/pipe -Igodot-mesa/src/mesa -Igodot-mesa/src/mesa/main -Igodot-mesa/src/mesa/program -Igodot-mesa/src/microsoft -Igodot-mesa/src/microsoft/compiler -Igodot-mesa/src/microsoft/spirv_to_dxil -Igodot-mesa/src/util -Igodot-mesa/src/util/format -Igodot-mesa/src/util/format/__pycache__ -Igodot-mesa/src/util/sha1 -Igodot-mesa/src/vulkan -Igodot-mesa/src/vulkan/runtime -Igodot-mesa/src/vulkan/util -Igodot-mesa/generated/src -Igodot-mesa/generated/src/compiler -Igodot-mesa/generated/src/compiler/nir -Igodot-mesa/generated/src/compiler/nir -Igodot-mesa/generated/src/compiler/nir -Igodot-mesa/generated/src/compiler/nir -Igodot-mesa/generated/src/compiler/spirv -Igodot-mesa/generated/src/util/format -I. -Ivulkan/include godot-mesa/src/microsoft/compiler/nir_to_dxil.c
    =====
    godot-mesa/src/microsoft/compiler/nir_to_dxil.c:5087:7: error: expected expression
     5087 |       const struct dxil_value* value = get_src(ctx, &intr->src[0], 0, nir_type_uint);
          |       ^
    godot-mesa/src/microsoft/compiler/nir_to_dxil.c:5088:45: error: use of undeclared identifier 'value'
     5088 |       store_dest_value(ctx, &intr->dest, 0, value);
          |                                             ^
    2 errors generated.

    =====
    scons: *** [godot-mesa/src/microsoft/compiler/nir_to_dxil.windows.arm64.o] Error 1
    scons: building terminated because of errors.
```

With these change I am able to build on a Surface Pro X without any issues.

Afterwords compiling godot itself looks like this:
```
$ scons  mingw_prefix=/clangarm64 LINKFLAGS="-lpng -lembree3.dll -L/clangarm64/lib/" CCFLAGS='-I/clangarm64/include/-v' CC=aarch64-w64-mingw32-gcc CXX=aarch64-w64-mingw32-g++ platform=windows builtin_embree=False builtin_libpng=False d3d12=True mesa_libs=<path to godot-nir-static> dxc_path=<path to dxc> opengl3=False vulkan=False use_volk=False
```

embree, and libpng included in the repo proved to be difficult to compile with. I opted to use the pre compiled versions available through my package manager.

This was a fun challenge, and I hope it is found to be useful.

PS this only worked on the current master of Godot (v4.3.dev.custom_build [13a0d6e9b]), the 4.2 branch would not compile.

### CODE REVIEW

File: SConstruct [hunk 1]
```diff
@@ -310,6 +310,15 @@ else:
     )
     env.Append(CFLAGS=["-std=c11"])
 
+# At this time the only version of mingw that runs on arm64 windows is aarch64-w64-mingw32.
+# These settings should take effect in a msys2 clangarm64 environment.
+if env["platform"] == "windows" and env["arch"] == "arm64" and env.get("use_mingw", False):
```
Comment (bruvzg) [inline SConstruct:315]: > env.get("use_mingw", False)

This condition probably should be the opposite, MinGW build (regardless if it's standalone or MSYS2 environment) should be run with `use_mingw=yes`.

**Comment by bruvzg** [comment]
> scons use_mingw=True use_clang_cl=True

`use_clang_cl` is MSVC only option, flag for MinGW/Clang is `use_llvm`.

**Comment by superxkooda** [comment]
> > scons use_mingw=True use_clang_cl=True
> 
> `use_clang_cl` is MSVC only option, flag for MinGW/Clang is `use_llvm`.

I re-ran with this option to be sure I didn't waist a bit of time, the changes were still needed to get it to compile. I updated my PR description and the commit message appropriately.

File: SConstruct (hunk 1 above)
Comment (superxkooda) [reply SConstruct]: I updated this to only check for use_mingw. Ran it both ways on my desktop, it happily built with or without any issues. please let me know if this is not what you suggested.

Thanks!

File: SConstruct [hunk 2]
```diff
@@ -310,6 +310,12 @@ else:
     )
     env.Append(CFLAGS=["-std=c11"])
 
+if env.get("use_mingw", False):
```
Comment (bruvzg) [inline SConstruct:313]:
```suggestion
if env.get("use_llvm", False):
```

This will not work with normal MinGW/GCC distributions, since there's no `timespec_get` and it's not using UCRT. Library will build, but Godot won't (linking will fail).

Or maybe it with adding a separate `use_ucrt` flag, since at least for x86-64, MinGW/clang can use both `UCRT` and `msvcrt`).

File: SConstruct [hunk 3]
```diff
@@ -310,6 +310,12 @@ else:
...
+    extra_defines += [
+            "HAVE_TIMESPEC_GET",
+            "_UCRT",
+            ]
```
Comment (bruvzg) [inline SConstruct:317]:
```suggestion
    extra_defines += [
        "HAVE_TIMESPEC_GET",
        "_UCRT",
    ]
```

File: SConstruct (hunk 2 above)
Comment (superxkooda) [reply SConstruct]: I do not have a strong opinion I can change it to check for use_ucrt if preferable.

**Review by bruvzg — APPROVED** [review]

**Comment by bruvzg** [comment]
Please squash the commits into one, see [Pull request workflow](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase).

**Comment by superxkooda** [comment]
> Please squash the commits into one, see [Pull request workflow](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase).

No problem.

**Comment by superxkooda** [comment]
done.

**Comment by bruvzg** [comment]
Thanks!
